name: Deploy to Azure app services as Docker
descripton: This is a custom GitHub action which will deploy to ACR and update App service with the latest docker image
inputs:
  docker_server_url:
    description: "Docker login server"
    required: true
    default: ""

  docker_server_username:
    description: "Docker login username"
    required: true
    default: ""

  docker_server_password:
    description: "Docker login password"
    required: true
    default: ""

  docker_image_name:
    description: "Docker image name"
    required: true
    default: ""

  github_username:
    description: "Github username"
    required: true
    default: ""

  github_pat:
    description: "Github pat"
    required: true
    default: ""

  resource_group:
    description: "Resource group"
    required: true
    default: ""

  app_service_withfloats_api:
    description: "Azure App Service Withfloats-api"
    required: true
    default: ""

  app_service_withfloats_api_createfp:
    description: "Azure App Service Withfloats-api"
    required: true
    default: ""

  app_service_withfloats_api_getfpdetails:
    description: "Azure App Service Withfloats-api"
    required: true
    default: ""

  app_service_withfloats_api_getkeywords:
    description: "Azure App Service Withfloats-api"
    required: true
    default: ""

  app_service_withfloats_api_search:
    description: "Azure App Service Withfloats-api"
    required: true
    default: ""

runs:
  using: "node12"
  main: "index.js"
