name: Deploy to AWS ECS cluster
descripton: This is a custom GitHub action which will deploy to ECR and update ECS with the "latest" docker image
inputs:

  access_key_id:
    description: "Access key ID for AWS login"
    required: true
    default: ""

  access_key_secret:
    description: "Access key secret for AWS login"
    required: true
    default: ""

  region:
    description: "Region for AWS login"
    required: true
    default: ""

  ecr_login:
    description: "ECR login command"
    required: true
    default: ""

  docker_image_name:
    description: "Name for your docker image"
    required: true
    default: ""

  docker_file_location:
    description: "Location where your dockerfile is present"
    required: true
    default: ""

  tag:
    description: "Tag for your docker  image"
    required: true
    default: ""

  cluster_name:
    description: "Name of the ECS cluster"
    required: true
    default: ""

  service_name:
    description: "Name of the service running in the ECS cluster"
    required: true
    default: ""
    
runs:
  using: 'node12'
  main: 'index.js'
